version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./laravel-project:/data
  # 追記
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./laravel-project:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data